import {
  ChartColumn,
  Bell,
  BookOpen,
  CalendarCheck,
  ClipboardCheck,
  ExternalLink,
  FileText,
  Flag,
  FolderOpen,
  HeartHandshake,
  House,
  LayoutDashboard,
  LifeBuoy,
  Link2,
  Lightbulb,
  MapPin,
  MessageCircle,
  MessageSquareText,
  Milestone,
  Search,
  Settings,
  ShieldCheck,
  Shuffle,
  Sparkles,
  Trophy,
  UserRound,
  UsersRound,
  Video,
  Wrench,
  type LucideProps,
} from "lucide-react";
import type { NavIcon as NavIconName } from "./nav-types";

const ICONS = {
  home: House,
  tips: Lightbulb,
  tracker: CalendarCheck,
  checkin: ClipboardCheck,
  profile: UserRound,
  resources: MapPin,
  journey: Milestone,
  trophy: Trophy,
  bell: Bell,
  messages: MessageCircle,
  coaching: HeartHandshake,
  files: FolderOpen,
  coach: Sparkles,
  video: Video,
  search: Search,
  book: BookOpen,
  help: LifeBuoy,
  users: UsersRound,
  shield: ShieldCheck,
  flag: Flag,
  chart: ChartColumn,
  settings: Settings,
  content: FileText,
  sms: MessageSquareText,
  survey: ClipboardCheck,
  shuffle: Shuffle,
  dashboard: LayoutDashboard,
  support: Wrench,
  external: ExternalLink,
  link: Link2,
} satisfies Record<NavIconName, React.ComponentType<LucideProps>>;

export function NavIcon({ name, ...props }: { name: NavIconName } & LucideProps) {
  const Icon = ICONS[name];
  return <Icon aria-hidden {...props} />;
}
