/**
 * Sample resources for local development and demos. Every organisation is
 * fictional; phone numbers use the reserved 555-01xx range and websites use
 * example.org. Coordinates are approximate neighbourhood centres.
 */
export type SeedResource = {
  guid: string;
  title: string;
  description: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  website?: string;
  contact: string;
  hours: string;
  eligibility?: string;
  scheduling?: string;
  covidUpdates?: string;
  insuranceStatus?: string;
  services?: string;
  tags: string[];
  lat: number;
  lng: number;
};

export const SEED_RESOURCES: SeedResource[] = [
  // Boston, MA
  {
    guid: "seed-001",
    title: "Harborview Community Health Center",
    description: "A neighborhood health center offering primary care, HIV care and same-day testing in a judgement-free setting.",
    address: "410 Tremont Street",
    city: "Boston",
    state: "MA",
    zip: "02116",
    website: "https://harborview-health.example.org",
    contact: "(617) 555-0142 · intake@harborview-health.example.org",
    hours: "Mon–Fri 8:30 am – 7 pm\nSat 9 am – 1 pm",
    eligibility: "Everyone welcome, regardless of insurance or immigration status. Sliding-scale fees available.",
    scheduling: "Walk-in testing until 5 pm on weekdays. Call or book online for care appointments.",
    insuranceStatus: "Accepts MassHealth, Medicare and most private plans. Free testing for everyone.",
    covidUpdates: "Masks available at the front desk. Telehealth visits offered for follow-ups.",
    services: "Primary care, HIV testing and treatment, PrEP, lab services, insurance enrollment help",
    tags: ["HIV testing", "PrEP", "Primary care", "Insurance help"],
    lat: 42.3496,
    lng: -71.0662,
  },
  {
    guid: "seed-002",
    title: "Back Bay Wellness Collective",
    description: "Peer-led support groups and one-on-one counseling for people living with HIV and their partners.",
    address: "22 Clarendon Street, Suite 3",
    city: "Boston",
    state: "MA",
    zip: "02116",
    website: "https://bbwellness.example.org",
    contact: "(617) 555-0118",
    hours: "Tue–Thu 11 am – 8 pm",
    eligibility: "Adults 18+ living with or affected by HIV.",
    scheduling: "Groups meet Tuesdays and Thursdays at 6 pm. Counseling by appointment.",
    insuranceStatus: "Free of charge.",
    services: "Support groups, individual counseling, peer mentoring",
    tags: ["Mental health", "Support groups", "LGBTQ+ services"],
    lat: 42.3474,
    lng: -71.0735,
  },
  {
    guid: "seed-003",
    title: "Fenway Food Share",
    description: "A client-choice food pantry with fresh produce, halal and vegetarian options.",
    address: "88 Queensberry Street",
    city: "Boston",
    state: "MA",
    zip: "02215",
    contact: "(617) 555-0167",
    hours: "Wed 2 pm – 6 pm\nSat 10 am – 1 pm",
    eligibility: "Open to anyone in need. Bring a bag if you can.",
    scheduling: "No appointment needed.",
    services: "Groceries, fresh produce, SNAP application help",
    tags: ["Food pantry", "Benefits help"],
    lat: 42.3425,
    lng: -71.0985,
  },
  {
    guid: "seed-004",
    title: "Dorchester Bay Housing Partners",
    description: "Housing search support, emergency rental help and case management.",
    address: "1520 Dorchester Avenue",
    city: "Dorchester",
    state: "MA",
    zip: "02122",
    website: "https://dbhousing.example.org",
    contact: "(617) 555-0133",
    hours: "Mon–Fri 9 am – 5 pm",
    eligibility: "Boston residents at risk of losing housing. Priority for people living with HIV.",
    scheduling: "Call to schedule an intake. Drop-in hours Mondays 1–4 pm.",
    insuranceStatus: "No insurance needed.",
    services: "Housing search, rental assistance, case management",
    tags: ["Housing", "Case management"],
    lat: 42.2981,
    lng: -71.0592,
  },
  {
    guid: "seed-005",
    title: "Jamaica Plain Legal Clinic",
    description: "Free legal help with housing, benefits, discrimination and immigration questions.",
    address: "3371 Washington Street",
    city: "Jamaica Plain",
    state: "MA",
    zip: "02130",
    website: "https://jplegal.example.org",
    contact: "(617) 555-0189",
    hours: "Mon, Wed 10 am – 6 pm",
    eligibility: "Low-income residents of Greater Boston.",
    scheduling: "Appointments only. Leave a message and a paralegal will call back within two business days.",
    services: "Legal aid, benefits appeals, discrimination complaints",
    tags: ["Legal aid", "Benefits help"],
    lat: 42.3097,
    lng: -71.1097,
  },
  {
    guid: "seed-006",
    title: "Cambridge Harm Reduction Hub",
    description: "Syringe services, naloxone, drug-checking strips and connections to treatment, no strings attached.",
    address: "12 Pearl Street",
    city: "Cambridge",
    state: "MA",
    zip: "02139",
    contact: "(617) 555-0104",
    hours: "Daily 10 am – 6 pm",
    eligibility: "Anyone who uses drugs, and their friends and family.",
    scheduling: "Walk in. Mobile outreach van Friday evenings.",
    insuranceStatus: "Free and anonymous.",
    services: "Naloxone, syringe services, HIV and hepatitis C testing, treatment referrals",
    tags: ["Harm reduction", "Substance use", "HIV testing"],
    lat: 42.3637,
    lng: -71.1022,
  },
  {
    guid: "seed-007",
    title: "Roxbury Women's Health Circle",
    description: "Care designed with and for women: sexual and reproductive health, prenatal care and HIV care.",
    address: "2201 Washington Street",
    city: "Roxbury",
    state: "MA",
    zip: "02119",
    website: "https://rwhc.example.org",
    contact: "(617) 555-0151",
    hours: "Mon–Fri 8 am – 6 pm",
    eligibility: "Women and gender-diverse people of all ages.",
    scheduling: "Same-week appointments. Childcare available during visits.",
    insuranceStatus: "Accepts MassHealth and most plans. Help enrolling on site.",
    covidUpdates: "Video visits available for most follow-ups.",
    services: "Gynecology, prenatal care, contraception, HIV care, STI testing",
    tags: ["Women's health", "Sexual health", "HIV care"],
    lat: 42.3294,
    lng: -71.0838,
  },
  {
    guid: "seed-008",
    title: "Crisis Text & Talk Line of New England",
    description: "Free, confidential emotional support by phone or text, any time.",
    address: "PO Box 555",
    city: "Boston",
    state: "MA",
    zip: "02101",
    contact: "Call or text (617) 555-0100",
    hours: "24 hours, 7 days",
    eligibility: "Anyone.",
    services: "Crisis support, safety planning, referrals",
    tags: ["Crisis line", "Mental health"],
    lat: 42.3601,
    lng: -71.0589,
  },
  // Philadelphia, PA
  {
    guid: "seed-009",
    title: "Liberty Bell Health Partners",
    description: "HIV specialty care, PrEP and pharmacy under one roof in Center City.",
    address: "1234 Walnut Street",
    city: "Philadelphia",
    state: "PA",
    zip: "19107",
    website: "https://libertybellhealth.example.org",
    contact: "(215) 555-0122",
    hours: "Mon–Fri 8 am – 8 pm\nSat 9 am – 2 pm",
    eligibility: "Everyone welcome.",
    scheduling: "PrEP same-day starts on weekdays before 3 pm.",
    insuranceStatus: "Accepts Medicaid, Medicare and private insurance. Patient assistance for the uninsured.",
    services: "HIV care, PrEP, PEP, pharmacy, nutrition counseling",
    tags: ["HIV care", "PrEP", "Pharmacy"],
    lat: 39.9489,
    lng: -75.1621,
  },
  {
    guid: "seed-010",
    title: "Kensington Recovery Commons",
    description: "Low-barrier recovery support, medication for opioid use disorder and peer coaching.",
    address: "3000 Kensington Avenue",
    city: "Philadelphia",
    state: "PA",
    zip: "19134",
    contact: "(215) 555-0171",
    hours: "Mon–Sat 7 am – 7 pm",
    eligibility: "Adults 18+.",
    scheduling: "Walk-in intake every morning 7–11 am.",
    insuranceStatus: "Medicaid accepted. No one turned away for inability to pay.",
    services: "Buprenorphine, methadone referrals, peer recovery coaching, naloxone",
    tags: ["Substance use", "Harm reduction"],
    lat: 39.9952,
    lng: -75.1246,
  },
  {
    guid: "seed-011",
    title: "West Philly Youth Drop-In",
    description: "A safe space for LGBTQ+ youth with meals, showers, testing and case management.",
    address: "4520 Baltimore Avenue",
    city: "Philadelphia",
    state: "PA",
    zip: "19143",
    website: "https://wpyouth.example.org",
    contact: "(215) 555-0148",
    hours: "Mon–Fri 2 pm – 9 pm",
    eligibility: "Young people ages 14–24.",
    scheduling: "Drop in. Testing Wednesdays 4–8 pm.",
    services: "Meals, showers, HIV testing, housing referrals, GED support",
    tags: ["LGBTQ+ services", "Youth services", "HIV testing"],
    lat: 39.9486,
    lng: -75.2131,
  },
  {
    guid: "seed-012",
    title: "Schuylkill Mental Health Associates",
    description: "Therapy and psychiatry with clinicians experienced in HIV, trauma and identity.",
    address: "200 South Broad Street, 8th floor",
    city: "Philadelphia",
    state: "PA",
    zip: "19102",
    contact: "(215) 555-0109",
    hours: "Mon–Thu 9 am – 8 pm\nFri 9 am – 4 pm",
    eligibility: "Adults 18+. Spanish-speaking clinicians available.",
    scheduling: "New clients usually seen within two weeks. Telehealth available.",
    insuranceStatus: "In network with most plans. Sliding scale available.",
    services: "Individual therapy, couples therapy, psychiatry",
    tags: ["Mental health", "Counseling"],
    lat: 39.9496,
    lng: -75.1643,
  },
  {
    guid: "seed-013",
    title: "North Philly Community Kitchen",
    description: "Hot lunches every weekday and a Saturday grocery table.",
    address: "2100 North Broad Street",
    city: "Philadelphia",
    state: "PA",
    zip: "19121",
    contact: "(215) 555-0181",
    hours: "Mon–Fri 11:30 am – 1:30 pm\nSat 9 am – 12 pm",
    eligibility: "Open to all.",
    services: "Hot meals, grocery distribution",
    tags: ["Food pantry"],
    lat: 39.9853,
    lng: -75.1557,
  },
  // New York, NY
  {
    guid: "seed-014",
    title: "Chelsea Sexual Health Clinic",
    description: "Fast, free STI and HIV testing with results by text, plus PrEP and PEP.",
    address: "303 West 20th Street",
    city: "New York",
    state: "NY",
    zip: "10011",
    website: "https://chelseash.example.org",
    contact: "(212) 555-0136",
    hours: "Mon–Fri 8:30 am – 3:30 pm",
    eligibility: "Ages 12 and up. No ID or insurance needed.",
    scheduling: "Walk-in. Arrive early: the line fills by 2 pm.",
    insuranceStatus: "Free.",
    covidUpdates: "COVID-19 vaccines available on Tuesdays.",
    services: "HIV testing, STI testing and treatment, PrEP, PEP, vaccines",
    tags: ["HIV testing", "Sexual health", "PrEP"],
    lat: 40.7434,
    lng: -74.0003,
  },
  {
    guid: "seed-015",
    title: "Harlem Hope Housing",
    description: "Supportive housing and rental assistance for New Yorkers living with HIV.",
    address: "125 West 125th Street",
    city: "New York",
    state: "NY",
    zip: "10027",
    contact: "(212) 555-0177",
    hours: "Mon–Fri 9 am – 5 pm",
    eligibility: "Manhattan residents living with HIV with income under 200% of the federal poverty level.",
    scheduling: "Intake by phone. Bring ID and proof of income to your first visit.",
    services: "Supportive housing, rental assistance, benefits navigation",
    tags: ["Housing", "Benefits help", "Case management"],
    lat: 40.8093,
    lng: -73.9473,
  },
  {
    guid: "seed-016",
    title: "Brooklyn Trans Health Collective",
    description: "Gender-affirming primary care, hormone therapy and peer support.",
    address: "495 Atlantic Avenue",
    city: "Brooklyn",
    state: "NY",
    zip: "11217",
    website: "https://btransh.example.org",
    contact: "(718) 555-0126",
    hours: "Tue–Sat 10 am – 7 pm",
    eligibility: "Trans, non-binary and gender-expansive people 16+.",
    scheduling: "Informed-consent hormone therapy. New patient visits within three weeks.",
    insuranceStatus: "Medicaid and most plans. Free support groups.",
    services: "Primary care, hormone therapy, HIV care, support groups, name change help",
    tags: ["Transgender health", "LGBTQ+ services", "Primary care"],
    lat: 40.6849,
    lng: -73.9796,
  },
  {
    guid: "seed-017",
    title: "Bronx Benefits Navigators",
    description: "Help applying for health insurance, SNAP, cash assistance and medication programs.",
    address: "2800 Grand Concourse",
    city: "Bronx",
    state: "NY",
    zip: "10458",
    contact: "(718) 555-0163",
    hours: "Mon–Fri 9 am – 6 pm",
    eligibility: "Bronx residents.",
    scheduling: "Walk-ins Monday and Wednesday. Other days by appointment.",
    services: "Medicaid enrollment, SNAP, ADAP applications",
    tags: ["Insurance help", "Benefits help"],
    lat: 40.8687,
    lng: -73.8933,
  },
  {
    guid: "seed-018",
    title: "Lower East Side Needle & Naloxone Exchange",
    description: "Harm reduction supplies, overdose response training and a calm place to rest.",
    address: "25 Allen Street",
    city: "New York",
    state: "NY",
    zip: "10002",
    contact: "(212) 555-0112",
    hours: "Daily 9 am – 9 pm",
    eligibility: "Anyone.",
    services: "Syringe services, naloxone, drug checking, showers",
    tags: ["Harm reduction", "Substance use"],
    lat: 40.7155,
    lng: -73.9919,
  },
  // Los Angeles, CA
  {
    guid: "seed-019",
    title: "Sunset Junction Health",
    description: "LGBTQ+-centered primary care, HIV care and behavioral health in Silver Lake.",
    address: "3900 Sunset Boulevard",
    city: "Los Angeles",
    state: "CA",
    zip: "90029",
    website: "https://sunsetjunction.example.org",
    contact: "(323) 555-0130",
    hours: "Mon–Fri 8 am – 7 pm",
    eligibility: "Everyone welcome.",
    scheduling: "Book online or call. Same-day PrEP on weekdays.",
    insuranceStatus: "Medi-Cal, Medicare and most private plans. Free Ryan White services.",
    services: "Primary care, HIV care, PrEP, behavioral health",
    tags: ["HIV care", "PrEP", "LGBTQ+ services", "Mental health"],
    lat: 34.0917,
    lng: -118.2803,
  },
  {
    guid: "seed-020",
    title: "South LA Family Pantry",
    description: "Weekly groceries plus diapers and hygiene kits for families.",
    address: "5800 South Vermont Avenue",
    city: "Los Angeles",
    state: "CA",
    zip: "90044",
    contact: "(323) 555-0175",
    hours: "Thu 3 pm – 7 pm\nSat 8 am – 12 pm",
    eligibility: "Open to all LA County residents.",
    services: "Groceries, diapers, hygiene kits, CalFresh help",
    tags: ["Food pantry", "Benefits help"],
    lat: 33.9876,
    lng: -118.2915,
  },
  {
    guid: "seed-021",
    title: "Westlake Legal Aid Project",
    description: "Know-your-rights workshops and free representation for tenants and workers.",
    address: "1550 West 8th Street",
    city: "Los Angeles",
    state: "CA",
    zip: "90017",
    contact: "(213) 555-0144",
    hours: "Mon–Fri 9 am – 5 pm",
    eligibility: "Low-income LA County residents. Services in English and Spanish.",
    scheduling: "Call the intake line; workshops every second Saturday.",
    services: "Tenant rights, workplace discrimination, immigration referrals",
    tags: ["Legal aid"],
    lat: 34.0555,
    lng: -118.2744,
  },
  {
    guid: "seed-022",
    title: "Long Beach Positive Living Center",
    description: "Case management, support groups and a medication adherence program.",
    address: "2017 East 4th Street",
    city: "Long Beach",
    state: "CA",
    zip: "90814",
    contact: "(562) 555-0129",
    hours: "Mon–Fri 9 am – 6 pm",
    eligibility: "Adults living with HIV in Long Beach and South Bay.",
    scheduling: "Groups Tuesdays 6 pm. Case managers by appointment.",
    insuranceStatus: "Free.",
    services: "Case management, support groups, adherence coaching, transportation vouchers",
    tags: ["Case management", "Support groups", "Transportation"],
    lat: 33.7708,
    lng: -118.1675,
  },
  // Houston, TX
  {
    guid: "seed-023",
    title: "Montrose Community Clinic",
    description: "Sexual health, HIV care and counseling in the heart of Montrose.",
    address: "1400 Westheimer Road",
    city: "Houston",
    state: "TX",
    zip: "77006",
    website: "https://montroseclinic.example.org",
    contact: "(713) 555-0138",
    hours: "Mon–Fri 9 am – 7 pm\nSat 10 am – 2 pm",
    eligibility: "Everyone welcome.",
    scheduling: "Walk-in testing. Appointments for care.",
    insuranceStatus: "Medicaid, Medicare and most plans. Sliding scale for the uninsured.",
    services: "HIV testing, HIV care, PrEP, counseling",
    tags: ["HIV testing", "HIV care", "PrEP", "Counseling"],
    lat: 29.7445,
    lng: -95.3957,
  },
  {
    guid: "seed-024",
    title: "Third Ward Food & Friends",
    description: "A community pantry and shared lunch table run by neighbors.",
    address: "3500 Dowling Street",
    city: "Houston",
    state: "TX",
    zip: "77004",
    contact: "(713) 555-0157",
    hours: "Tue & Fri 10 am – 2 pm",
    eligibility: "Open to all.",
    services: "Groceries, community lunch",
    tags: ["Food pantry"],
    lat: 29.7294,
    lng: -95.3616,
  },
  {
    guid: "seed-025",
    title: "Bayou City Rides to Care",
    description: "Free rides to medical appointments and pharmacy pick-ups.",
    address: "900 Commerce Street",
    city: "Houston",
    state: "TX",
    zip: "77002",
    contact: "(713) 555-0120",
    hours: "Mon–Fri 7 am – 6 pm",
    eligibility: "Harris County residents with a medical appointment. Book at least 48 hours ahead.",
    scheduling: "Call to book. Same-day rides for urgent pharmacy needs when drivers are available.",
    services: "Rides to appointments, pharmacy pick-ups",
    tags: ["Transportation"],
    lat: 29.7633,
    lng: -95.3605,
  },
  {
    guid: "seed-026",
    title: "Gulf Coast Crisis & Support Line",
    description: "Round-the-clock support for anyone in emotional distress or thinking about suicide.",
    address: "PO Box 555",
    city: "Houston",
    state: "TX",
    zip: "77001",
    contact: "Call or text (713) 555-0199",
    hours: "24 hours, 7 days",
    eligibility: "Anyone.",
    services: "Crisis support, counseling referrals",
    tags: ["Crisis line", "Mental health"],
    lat: 29.7604,
    lng: -95.3698,
  },
  {
    guid: "seed-027",
    title: "Heights Women & Families Health",
    description: "Prenatal care, family planning and HIV prevention for women and families.",
    address: "1920 North Shepherd Drive",
    city: "Houston",
    state: "TX",
    zip: "77008",
    contact: "(713) 555-0165",
    hours: "Mon–Fri 8 am – 5 pm",
    eligibility: "Women and families.",
    scheduling: "Appointments within a week. Evening clinic Thursdays until 8 pm.",
    insuranceStatus: "Medicaid, CHIP and most plans.",
    services: "Prenatal care, family planning, PrEP, pediatric care",
    tags: ["Women's health", "Sexual health", "PrEP"],
    lat: 29.8016,
    lng: -95.4103,
  },
];
