/**
 * Starter glossary for local development: plain-language health, HIV and
 * rights terms written for this app (not copied from the old site). The
 * study's own 76 entries arrive with the data migration.
 */
export const SEED_GLOSSARY: { name: string; definition: string }[] = [
  { name: "ADA", definition: "<p>The <strong>Americans with Disabilities Act</strong>, a federal law that protects people with disabilities from discrimination at work, in public places and in services. HIV is covered as a disability under the ADA.</p>" },
  { name: "ADAP", definition: "<p>The <strong>AIDS Drug Assistance Program</strong>. State programs that help people living with HIV pay for HIV medicines when they have limited or no insurance.</p>" },
  { name: "Adherence", definition: "<p>Taking your medicine the way it was prescribed: the right dose, at the right time, every day. Good adherence keeps HIV under control and helps prevent drug resistance.</p>" },
  { name: "Affordable Care Act", definition: "<p>A 2010 US law (also called the ACA or \"Obamacare\") that expanded health insurance options. Insurers can't refuse to cover you or charge you more because of a pre-existing condition such as HIV.</p>" },
  { name: "Ageism", definition: "<p>Stereotyping or treating people unfairly because of their age.</p>" },
  { name: "AIDS", definition: "<p><strong>Acquired immunodeficiency syndrome</strong>, the most advanced stage of HIV infection, when the immune system is badly damaged. With today's treatment, most people with HIV never develop AIDS.</p>" },
  { name: "Ally", definition: "<p>Someone who actively supports people from a group they aren't part of, for example by speaking up against stigma or discrimination.</p>" },
  { name: "AMAB/AFAB/ASAB", definition: "<p>Short for <em>assigned male at birth</em>, <em>assigned female at birth</em> and <em>assigned sex at birth</em>. These terms describe the sex recorded when someone was born, which may differ from their gender.</p>" },
  { name: "Antiretroviral therapy (ART)", definition: "<p>The combination of HIV medicines taken every day to control the virus. ART can't cure HIV, but it helps people live long, healthy lives and prevents passing HIV to sexual partners.</p>" },
  { name: "Cis", definition: "<p>Short for <strong>cisgender</strong>: a person whose gender identity matches the sex they were assigned at birth.</p>" },
  { name: "Civil rights", definition: "<p>The rights everyone has to equal treatment and protection under the law, including in work, housing, education and public services.</p>" },
  { name: "CD4 count", definition: "<p>A blood test that counts CD4 cells, the immune cells HIV attacks. A higher CD4 count generally means a stronger immune system.</p>" },
  { name: "Co-insurance", definition: "<p>The share of a medical bill you pay after meeting your deductible, shown as a percentage. With 20% co-insurance you pay $20 of a $100 bill and your plan pays $80.</p>" },
  { name: "Co-pay", definition: "<p>A fixed amount you pay for a covered service, such as $15 for a doctor visit or a prescription.</p>" },
  { name: "Condom", definition: "<p>A thin barrier worn during sex that helps prevent HIV, other STIs and pregnancy. External condoms go on the penis; internal condoms go inside the vagina or anus.</p>" },
  { name: "Deductible", definition: "<p>The amount you pay for covered care each year before your insurance starts to pay.</p>" },
  { name: "Disclosure", definition: "<p>Choosing to tell someone about your HIV status. It's a personal decision; you get to decide who, when and how.</p>" },
  { name: "Discrimination", definition: "<p>Treating someone unfairly because of who they are, for example their HIV status, race, gender, sexuality, age or disability.</p>" },
  { name: "Drug resistance", definition: "<p>When HIV changes so that some medicines no longer work against it. Taking medicine consistently helps prevent resistance.</p>" },
  { name: "Equal Employment Opportunity Commission", definition: "<p>The <strong>EEOC</strong>, the federal agency that enforces laws against discrimination at work. You can file a complaint with it if you were treated unfairly by an employer.</p>" },
  { name: "Fair housing", definition: "<p>Laws that make it illegal to refuse, overcharge or mistreat renters and buyers because of race, disability (including HIV), sex, religion, family status or national origin.</p>" },
  { name: "Family and Medical Leave Act", definition: "<p>The <strong>FMLA</strong>, a federal law that lets many workers take up to 12 weeks of unpaid, job-protected leave a year for serious health conditions or family care.</p>" },
  { name: "Gender-affirming care", definition: "<p>Health care that supports a person's gender identity, such as hormone therapy, surgery, voice therapy or mental health care.</p>" },
  { name: "Harm reduction", definition: "<p>Practical, respectful approaches that lower the risks of drug use and sex without requiring people to stop, such as naloxone, clean syringes and condoms.</p>" },
  { name: "Hate crime", definition: "<p>A crime committed because of bias against someone's race, religion, disability, sexual orientation, gender identity or other characteristic.</p>" },
  { name: "Hepatitis B virus (HBV)", definition: "<p>A virus that infects the liver. It spreads through blood, sex and from parent to baby. A safe vaccine prevents it and treatment can control it.</p>" },
  { name: "Hepatitis C virus (HCV)", definition: "<p>A virus that infects the liver, mostly spread through blood (for example, sharing needles). Most people can be cured with 8 to 12 weeks of pills.</p>" },
  { name: "HIV", definition: "<p>The <strong>human immunodeficiency virus</strong>, which attacks the immune system. There's no cure yet, but daily treatment keeps HIV under control.</p>" },
  { name: "Houselessness", definition: "<p>Not having a stable, safe place to live. Many people prefer this word to \"homelessness\".</p>" },
  { name: "HRT", definition: "<p><strong>Hormone replacement therapy</strong> (or hormone therapy): medicines such as estrogen or testosterone. It's part of gender-affirming care for many trans and non-binary people, and also used during menopause.</p>" },
  { name: "In-network", definition: "<p>Doctors, clinics and pharmacies that have an agreement with your insurance plan. Care in-network usually costs you less.</p>" },
  { name: "Intramuscular", definition: "<p>Given as an injection into a muscle. Some long-acting HIV treatment and prevention medicines are given this way.</p>" },
  { name: "Intravenous", definition: "<p>Into a vein, for example an IV drip or an injection.</p>" },
  { name: "Long-acting injectable", definition: "<p>A medicine given as a shot every one or two months instead of a daily pill. There are long-acting options for both HIV treatment and PrEP.</p>" },
  { name: "Medicaid", definition: "<p>A public health insurance program for people with low incomes, run by each state. Names differ by state (for example MassHealth or Medi-Cal).</p>" },
  { name: "Medicare", definition: "<p>Federal health insurance for people 65 and older and for some younger people with disabilities.</p>" },
  { name: "Medication-assisted treatment", definition: "<p>Treatment for opioid or alcohol use disorder that combines medicine (such as buprenorphine or methadone) with counseling and support.</p>" },
  { name: "Methadone", definition: "<p>A long-acting medicine used to treat opioid use disorder by easing cravings and withdrawal. It's given through licensed treatment programs.</p>" },
  { name: "Naloxone (Narcan)", definition: "<p>A medicine that can reverse an opioid overdose. It comes as a nasal spray anyone can use, and many pharmacies give it out without a prescription.</p>" },
  { name: "Navigator", definition: "<p>A trained person who helps you find your way through health care and services, from booking appointments to getting insurance or medicine.</p>" },
  { name: "Non-binary", definition: "<p>A gender identity that isn't only man or only woman.</p>" },
  { name: "Opioids", definition: "<p>A group of drugs that includes prescription painkillers, heroin and fentanyl. They relieve pain but can cause dependence and overdose.</p>" },
  { name: "Out-of-network", definition: "<p>Providers that don't have an agreement with your insurance plan. Visits usually cost more, or may not be covered.</p>" },
  { name: "Out-of-pocket", definition: "<p>What you pay yourself for health care, including deductibles, co-pays and co-insurance. Most plans have a yearly out-of-pocket maximum.</p>" },
  { name: "Patient advocate", definition: "<p>Someone who helps you speak up for your needs in health care, understand your options and resolve problems.</p>" },
  { name: "PEP", definition: "<p><strong>Post-exposure prophylaxis</strong>: HIV medicines taken for 28 days after a possible exposure to HIV. Start as soon as possible, and within 72 hours.</p>" },
  { name: "Person who injects drugs", definition: "<p>Person-first language for someone who injects drugs. It puts the person before the behavior.</p>" },
  { name: "Premium", definition: "<p>The amount you pay every month to have health insurance, whether or not you use care.</p>" },
  { name: "PrEP", definition: "<p><strong>Pre-exposure prophylaxis</strong>: medicine taken by people who don't have HIV to prevent getting it. It comes as a daily pill or a long-acting shot and is highly effective.</p>" },
  { name: "Racism", definition: "<p>Prejudice, discrimination or unfair systems that disadvantage people because of their race or ethnicity.</p>" },
  { name: "Ryan White program", definition: "<p>A federal program that pays for HIV care, medicine and support services for people with low incomes who are uninsured or underinsured.</p>" },
  { name: "Serodiscordant couple", definition: "<p>A couple where one partner has HIV and the other doesn't (also called a mixed-status couple).</p>" },
  { name: "Serostatus", definition: "<p>Whether a person has tested positive or negative for a virus such as HIV.</p>" },
  { name: "Sex work", definition: "<p>Exchanging sexual services for money or goods.</p>" },
  { name: "Social inequality", definition: "<p>Unequal access to resources, opportunities and power between groups in society, for example in income, housing, education or health care.</p>" },
  { name: "STI", definition: "<p><strong>Sexually transmitted infection</strong>, such as chlamydia, gonorrhea or syphilis. Many have no symptoms, so regular testing matters. Most are easy to treat.</p>" },
  { name: "Stigma", definition: "<p>Negative beliefs and attitudes about a group of people, such as people living with HIV. Stigma can make people feel ashamed or keep them from getting care.</p>" },
  { name: "Title IX", definition: "<p>A federal law that bans sex discrimination, including sexual harassment, in schools and education programs that receive federal money.</p>" },
  { name: "Title VII", definition: "<p>Part of the Civil Rights Act of 1964 that bans job discrimination based on race, color, religion, sex (including sexual orientation and gender identity) and national origin.</p>" },
  { name: "Trans/Transgender", definition: "<p>Describes a person whose gender identity is different from the sex they were assigned at birth.</p>" },
  { name: "Transphobia", definition: "<p>Fear, hatred or discrimination toward transgender people.</p>" },
  { name: "U=U", definition: "<p><strong>Undetectable = Untransmittable.</strong> A person living with HIV who keeps an undetectable viral load by taking treatment does not pass HIV to sexual partners.</p>" },
  { name: "Undetectable/Virally suppressed", definition: "<p>When HIV treatment lowers the amount of virus in the blood so much that standard tests can't measure it. It keeps you healthy and means HIV can't be passed on through sex.</p>" },
  { name: "Unemployment/Underemployment", definition: "<p>Not having a job when you want one, or working fewer hours or in a lower-skilled job than you want or need.</p>" },
  { name: "Viral load", definition: "<p>A blood test that measures how much HIV is in your blood. The goal of treatment is an undetectable viral load.</p>" },
  { name: "White privilege", definition: "<p>Unearned advantages that white people have in society because of racism, whether or not they seek them.</p>" },
  { name: "Window period", definition: "<p>The time between a possible exposure to HIV and when a test can reliably detect it. It depends on the test, usually between 10 days and 3 months.</p>" },
];
